Repository Happynyamy/Happiggy-bank-iOS, pull requests merged in 2022-04, with the labels that each got.

#97 [feat] 홈뷰컨트롤러, 보틀뷰컨트롤러 리팩토링 #96
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewBottleDatePickerViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewNoteDatePickerViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift
Labels: enhancement

#100 [feat] 개발자에게 메일 보내기 구현 #95
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/ViewController/SettingsViewController.swift
Labels: enhancement

#117 [feat] 저금통 생성 화면 UI 변경 및 기능 추가 #108
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Happiggy-bank/Happiggy-bank/Assets.xcassets/background-color/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/background-color/backgroundColor.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/label-text-colors/homeLabelColor.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/label-text-colors/mainLabelColor.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/label-text-colors/primaryGreen.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/label-text-colors/subLabelColor.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift
  Happiggy-bank/Happiggy-bank/Extensions/UIColor+AssetColors.swift
  Happiggy-bank/Happiggy-bank/Model/NewBottle.swift
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewBottleDatePickerViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewBottleMessageFieldViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewBottleNameFieldViewController.swift
  Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift
  Happiggy-bank/Happiggy-bank/ViewModel/NewBottleDatePickerViewModel.swift
Labels: enhancement

#111 [fix] 저금통 리스트 탭 누른 뒤 개봉하는 경우 쪽지 리스트로 넘어가지 않는 문제 해결 #109
  Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift
Labels: bug

#121 [feat] 저금통 리스트 UI 변경 #120
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Storyboard/BottleCell.xib
  Happiggy-bank/Happiggy-bank/Subview/BottleCell.swift
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift
Labels: enhancement

#126 [fix] 내비게이션 버튼 크기, 위치 조정을 위해 이미지 에셋 svg에서 png로 교체
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/back.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/back.imageset/Vector 6-1.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/back.imageset/Vector 6-2.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/back.imageset/Vector 6-3.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/back.imageset/btn_next-1.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/back.imageset/btn_next-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/back.imageset/btn_next-2.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/back.imageset/btn_next-2.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/back.imageset/btn_next-3.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/checkmark.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/checkmark.imageset/btn_check-1.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/checkmark.imageset/btn_check-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/checkmark.imageset/btn_check-2.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/checkmark.imageset/btn_check-3.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/checkmark.imageset/btn_check-4.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/checkmark.imageset/btn_check-5.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/checkmark.imageset/btn_check.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/checkmark.imageset/btn_check.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/next.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/next.imageset/Vector 6-1.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/next.imageset/Vector 6-2.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/next.imageset/Vector 6.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/next.imageset/btn_next-1.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/next.imageset/btn_next-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/next.imageset/btn_next-2.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/next.imageset/btn_next.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/next.imageset/btn_next.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/xmark.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/xmark.imageset/btn_close-1.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/xmark.imageset/btn_close-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/xmark.imageset/btn_close-2.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/xmark.imageset/btn_close-3.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/xmark.imageset/btn_close-4.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/xmark.imageset/btn_close-5.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/xmark.imageset/btn_close.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/xmark.imageset/btn_close.svg
Labels: enhancement

#129 [feat] 저금통 개봉 애니메이션 수정 #128
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/Enum/TabItem.swift
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleMessageViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
  Happiggy-bank/Happiggy-bank/ViewModel/BottleListViewModel.swift
Labels: enhancement

#139 [feat] 코어데이터 에러 알림 처리 #136
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/CoreData/PersistenceStore.swift
  Happiggy-bank/Happiggy-bank/Extensions/UIVIewController+TopMostViewController.swift
  Happiggy-bank/Happiggy-bank/Extensions/UIWindowScene+TopMostViewController.swift
  Happiggy-bank/Happiggy-bank/SceneDelegate.swift
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/ViewController/ErrorViewController.swift
Labels: enhancement

#140 [feat] 세로모드 고정 #84
  Happiggy-bank/Happiggy-bank/AppDelegate.swift
Labels: enhancement

#141 [feat] 런치스크린 추가 #122
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/LaunchScreen.storyboard
Labels: enhancement

#152 [feat] 앱 아이콘 추가
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/100.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/1024.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/114.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/120.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/128.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/144.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/152.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/16.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/167.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/172.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/180.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/196.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/20.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/216.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/256.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/29.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/32.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/40.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/48.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/50.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/512.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/55.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/57.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/58.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/60.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/64.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/72.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/76.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/80.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/87.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/88.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: enhancement

#158 [chore] test flight 1.0.0 준비
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
Labels: chore

#162 [chore] 앱 이름 변경, 버전 0.0.0 #159
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
Labels: chore

#177 [feat] 새로운 쪽지 텍스트뷰에 플레이스홀더 추가 #176
  Happiggy-bank/Happiggy-bank/Extensions/UIView+FadeInOut.swift
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift
Labels: enhancement

#179 [fix] 새로운 쪽지 날짜 피커 경고 라벨 사라지지 않는 현상 해결 #178
  Happiggy-bank/Happiggy-bank/ViewController/NewNoteDatePickerViewController.swift
Labels: bug

#183 [refactor] 내비게이션 바 투명화 익스텐션 생성
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/Extensions/UINavigationBar+Clear.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleNameEditViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/InformationTextViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewBottleDatePickerViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewBottleMessageFieldViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewBottleNameFieldViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewNoteDatePickerViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/SettingsViewController.swift
Labels: refactor

#182 [fix] 노티피케이션 알림 반복 현상 수정 및 D-day 업데이트 정상화 #168, #181
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleMessageViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
  Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift
Labels: bug

#186 [feat] 에러 뷰 컨트롤러에 코어 데이터 에러 디버깅용 문구 추가 #163
  Happiggy-bank/Happiggy-bank/CoreData/PersistenceStore.swift
  Happiggy-bank/Happiggy-bank/SceneDelegate.swift
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/ViewController/ErrorViewController.swift
Labels: enhancement

#187 [docs] grid.swift 파일에 라이선스 내용 추가
  Happiggy-bank/Happiggy-bank/Utils/Grid.swift
Labels: docs

#188 [feat] 팀 이름, 팀 메일 주소 변경
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/ViewModel/CustomerServiceViewModel.swift
Labels: enhancement

#189 [chore] 버전 1.0.0 출시 준비
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
Labels: chore

#191 [docs] 버전 1.0.0 리드미 업데이트
  README.md
Labels: docs

#194 [hotfix] 새로운 저금통 개봉 메시지 누락 문제 해결 #193
  Happiggy-bank/Happiggy-bank/ViewController/NewBottleMessageFieldViewController.swift
Labels: bug

#196 [hotfix] 저금통 개봉 애니메이션 뷰 라벨들 잘리는 현상 수정 #195
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
Labels: bug

#199 [chore] version 1.0.1 업데이트
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
Labels: chore

#200 [docs] 리드미 팀 사진 업데이트
  README.md
Labels: docs
