Repository Happynyamy/Happiggy-bank-iOS, pull requests merged in 2022-03, with the labels that each got.

#19 [chore] SwiftLint 경로 문제로 build phase run script 변경 #17
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
Labels: chore

#25 [feat] BottleViewController 스토리보드로 전환 및 뷰모델 코어데이터와 연동 #24
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift
  Happiggy-bank/Happiggy-bank/Extensions/Calendar+Duration.swift
  Happiggy-bank/Happiggy-bank/Model/Bottle.swift
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/View/BottleImageView.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
  Happiggy-bank/Happiggy-bank/ViewModel/BottleViewModel.swift
Labels: enhancement

#27 [feat] 쪽지 추가를 위한 뷰 컨트롤러들 생성 및 연결 #26
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/Extensions/CATransition+PopupAnimation.swift
  Happiggy-bank/Happiggy-bank/Extensions/UIViewController+FadeOut.swift
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewNoteColorPickerViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewNoteDatePickerViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewNotePopupViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift
Labels: enhancement

#29 [feat] 쪽지 추가 날짜 피커 뷰 구성 #26
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/Assets.xcassets/NoteColors/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/NoteColors/noteGreen.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/NoteColors/notePink.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/NoteColors/notePurple.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/NoteColors/noteWhite.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/NoteColors/noteYellow.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift
  Happiggy-bank/Happiggy-bank/Enum/DateFormat.swift
  Happiggy-bank/Happiggy-bank/Extensions/Date+Formatted.swift
  Happiggy-bank/Happiggy-bank/Extensions/NSManagedObject+EntityName.swift
  Happiggy-bank/Happiggy-bank/Extensions/NSObject+Name.swift
  Happiggy-bank/Happiggy-bank/Model/NoteDatePickerData.swift
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Storyboard/NewNoteDatePickerRowView.xib
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/View/NewNoteDatePickerRowView.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewNoteDatePickerViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NotesViewController.swift
  Happiggy-bank/Happiggy-bank/ViewModel/NewNoteDatePickerViewModel.swift
Labels: enhancement

#33 [fix] 새로운 저금통 기간 피커에서 저장 버튼 누르면 충돌 발생하는 문제 수정 #32
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
Labels: bug

#34 [feat] 쪽지 추가 텍스트 뷰 구성 #26
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/Button/ColorButton.swift
  Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift
  Happiggy-bank/Happiggy-bank/CoreData/Note+CoreDataClass.swift
  Happiggy-bank/Happiggy-bank/Enum/NoteColor.swift
  Happiggy-bank/Happiggy-bank/Extensions/Date+Formatted.swift
  Happiggy-bank/Happiggy-bank/Model/NewNote.swift
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/View/NewNotePopupTopBar.swift
  Happiggy-bank/Happiggy-bank/View/NoteTextView.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewNoteColorPickerViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewNoteDatePickerViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewNotePopupViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift
Labels: enhancement

#39 [feat] 쪽지 리스트 구현 #35
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift
  Happiggy-bank/Happiggy-bank/Enum/DateFormat.swift
  Happiggy-bank/Happiggy-bank/Extensions/Date+Formatted.swift
  Happiggy-bank/Happiggy-bank/Extensions/String+BoldAttributedString.swift
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Storyboard/NoteCell.xib
  Happiggy-bank/Happiggy-bank/Subview/NoteCell.swift
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewNoteDatePickerViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NoteListViewController.swift
  Happiggy-bank/Happiggy-bank/ViewModel/NewNoteDatePickerViewModel.swift
  Happiggy-bank/Happiggy-bank/ViewModel/NoteListViewModel.swift
Labels: enhancement

#40 [feat] 저금통 리스트 #36
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/Assets.xcassets/bottle.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/bottle.imageset/bottle.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/bottleCellBackground.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/bottleCellBackground.imageset/bottleCellBackground.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/bottleInList.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/bottleInList.imageset/bottleInList.png
  Happiggy-bank/Happiggy-bank/Assets.xcassets/cap.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/cap.imageset/cap.png
  Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift
  Happiggy-bank/Happiggy-bank/Enum/DateFormat.swift
  Happiggy-bank/Happiggy-bank/Extensions/Date+Formatted.swift
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Storyboard/BottleCell.xib
  Happiggy-bank/Happiggy-bank/Subview/BottleCell.swift
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift
  Happiggy-bank/Happiggy-bank/ViewModel/BottleListViewModel.swift
  Happiggy-bank/Happiggy-bank/ViewModel/NewNoteDatePickerViewModel.swift
  Happiggy-bank/Happiggy-bank/ViewModel/NoteListViewModel.swift
Labels: enhancement

#42 [feat] 쪽지 리스트 UI 디자인 반영, 애니메이션 추가 #35
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/Assets.xcassets/NoteColors/noteGreen.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/NoteColors/notePink.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/NoteColors/notePurple.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/NoteColors/noteYellow.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/NoteHighlightColors/noteHighlightGreen.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/NoteHighlightColors/noteHighlightPink.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/NoteHighlightColors/noteHighlightPurple.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/NoteHighlightColors/noteHighlightWhite.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/NoteHighlightColors/noteHighlightYellow.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteGreen.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteGreen.imageset/img_note_green-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteGreen.imageset/img_note_green-2.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteGreen.imageset/img_note_green.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNotePink.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNotePink.imageset/img_note_pink-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNotePink.imageset/img_note_pink-2.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNotePink.imageset/img_note_pink.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNotePurple.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNotePurple.imageset/img_note_purple-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNotePurple.imageset/img_note_purple-2.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNotePurple.imageset/img_note_purple.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteWhite.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteWhite.imageset/img_note_green-2.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteWhite.imageset/img_note_green-3.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteWhite.imageset/img_note_green-4.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteYellow.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteYellow.imageset/img_note_yellow-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteYellow.imageset/img_note_yellow-2.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteYellow.imageset/img_note_yellow.svg
  Happiggy-bank/Happiggy-bank/Extensions/CGFloat+Values.swift
  Happiggy-bank/Happiggy-bank/Extensions/NSMutableAttributedString+ColorBold.swift
  Happiggy-bank/Happiggy-bank/Extensions/String+BoldAttributedString.swift
  Happiggy-bank/Happiggy-bank/Extensions/String+EmptyString.swift
  Happiggy-bank/Happiggy-bank/Extensions/String+NSMutableAttributedStringify.swift
  Happiggy-bank/Happiggy-bank/Storyboard/NoteCell.xib
  Happiggy-bank/Happiggy-bank/Subview/NoteCell.swift
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/View/NotesViewCell.swift
  Happiggy-bank/Happiggy-bank/ViewController/NoteListViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NotesViewController.swift
  Happiggy-bank/Happiggy-bank/ViewModel/BottleListViewModel.swift
  Happiggy-bank/Happiggy-bank/ViewModel/NewNoteDatePickerViewModel.swift
  Happiggy-bank/Happiggy-bank/ViewModel/NoteListViewModel.swift
  Happiggy-bank/Happiggy-bank/ViewModel/NotesViewModel.swift
Labels: enhancement

#51 [fix] 쪽지 리스트에서 셀 내부 뷰들의 크기 및 애니메이션 버그 수정 #50
  Happiggy-bank/Happiggy-bank/Storyboard/NoteCell.xib
  Happiggy-bank/Happiggy-bank/Subview/NoteCell.swift
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
Labels: enhancement

#52 [feat] 에셋 다시 추가 및 설정 변경 #44
  Happiggy-bank/Happiggy-bank/Assets.xcassets/label-text-colors/customGray.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/label-text-colors/placeholderTextColor.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/label-text-colors/primaryLabelColor.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/label-text-colors/secondaryLabelColor.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/label-text-colors/warningLabelColor.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteGreen.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteGreen.imageset/img_note_green-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteGreen.imageset/img_note_green-2.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNotePink.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNotePink.imageset/img_note_pink-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNotePink.imageset/img_note_pink-2.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNotePurple.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNotePurple.imageset/img_note_purple-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNotePurple.imageset/img_note_purple-2.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteWhite.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteWhite.imageset/img_note_green-3.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteWhite.imageset/img_note_green-4.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteYellow.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteYellow.imageset/img_note_yellow-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/list-note-images/listNoteYellow.imageset/img_note_yellow-2.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/noteGreen.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/noteGreen.imageset/초록-3.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/noteGreen.imageset/초록-4.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/notePink.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/notePink.imageset/분홍-3.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/notePink.imageset/분홍-4.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/notePurple.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/notePurple.imageset/보라-3.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/notePurple.imageset/보라-4.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/noteWhite.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/noteWhite.imageset/하양-3.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/noteWhite.imageset/하양-4.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/noteYellow.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/noteYellow.imageset/노랑-3.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/noteYellow.imageset/노랑-4.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/text-view-note-images/textViewNoteGreen.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/text-view-note-images/textViewNoteGreen.imageset/img_line01_green-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/text-view-note-images/textViewNoteGreen.imageset/img_line01_green-2.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/text-view-note-images/textViewNotePink.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/text-view-note-images/textViewNotePink.imageset/img_line01_pink-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/text-view-note-images/textViewNotePink.imageset/img_line01_pink-2.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/text-view-note-images/textViewNotePurple.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/text-view-note-images/textViewNotePurple.imageset/img_line01_purple-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/text-view-note-images/textViewNotePurple.imageset/img_line01_purple-2.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/text-view-note-images/textViewNoteWhite.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/text-view-note-images/textViewNoteWhite.imageset/img_line01_white-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/text-view-note-images/textViewNoteWhite.imageset/img_line01_white-2.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/text-view-note-images/textViewNoteYellow.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/text-view-note-images/textViewNoteYellow.imageset/img_line01_yellow-1.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/text-view-note-images/textViewNoteYellow.imageset/img_line01_yellow-2.svg
Labels: enhancement

#64 [feat] 홈 화면, 저금통 화면 뷰 구성 #63
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Subview/NoteView.swift
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/Utils/Gravity.swift
  Happiggy-bank/Happiggy-bank/View/BottleNoteView.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
  Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift
Labels: enhancement

#62 [feat] 저금통 리스트 셀에 쪽지 이미지들을 담은 그리드 추가, 셀 라벨 색상 적용 #43 #36
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift
  Happiggy-bank/Happiggy-bank/Extensions/CGSize+Area.swift
  Happiggy-bank/Happiggy-bank/Storyboard/BottleCell.xib
  Happiggy-bank/Happiggy-bank/Subview/BottleCell.swift
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/Utils/Grid.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift
  Happiggy-bank/Happiggy-bank/ViewModel/BottleListViewModel.swift
Labels: enhancement

#66 [feat] 홈 화면 저금통 뷰 그리드 추가 #65
  Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Subview/BottleCell.swift
  Happiggy-bank/Happiggy-bank/Subview/NoteView.swift
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/Utils/Grid.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift
  Happiggy-bank/Happiggy-bank/ViewModel/BottleViewModel.swift
Labels: enhancement

#69 [feat] 쪽지리스트 전체 개봉 버튼, 쪽지 개수 라벨 구현, 쪽지 내용 라벨 행간 및 자간 조정 #54 #55 #58 #35
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/noteGreen.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/notePink.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/notePurple.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/noteWhite.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/note-images/noteYellow.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Button/CapsuleButton.swift
  Happiggy-bank/Happiggy-bank/Extensions/UILabel+ParagraphStyle.swift
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Storyboard/CapsuleButton.xib
  Happiggy-bank/Happiggy-bank/Subview/NoteCell.swift
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/ViewController/NoteListViewController.swift
  Happiggy-bank/Happiggy-bank/ViewModel/NoteListViewModel.swift
Labels: enhancement

#71 [feat] 코어데이터 작동 확인, 목 데이터 추가 #48
  Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift
  Happiggy-bank/Happiggy-bank/CoreData/PersistenceStore.swift
  Happiggy-bank/Happiggy-bank/SceneDelegate.swift
  Happiggy-bank/Happiggy-bank/Subview/BottleCell.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/HomeViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewBottleDatePickerViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewNoteTextViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NoteListViewController.swift
  Happiggy-bank/Happiggy-bank/ViewModel/BottleListViewModel.swift
  Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift
Labels: enhancement

#74 [feat] 쪽지 리스트 컬렉션 뷰로 변경, fetched result controller 적용 #72 #73
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/CoreData/Note+CoreDataClass.swift
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Subview/BottleCell.swift
  Happiggy-bank/Happiggy-bank/Subview/TagCell.swift
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/Utils/TagViewFlowLayout.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleListViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NoteListViewController.swift
  Happiggy-bank/Happiggy-bank/ViewModel/BottleListViewModel.swift
  Happiggy-bank/Happiggy-bank/ViewModel/NoteListViewModel.swift
Labels: enhancement

#79 [feat] 환경 설정 뷰 구성 및 알림 설정, 앱 버전 확인을 위한 셀 생성 #60
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/tabBarSettingsNormal.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/tabBarSettingsNormal.imageset/btn_setting_nor.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/tabBarSettingsSelected.imageset/Contents.json
  Happiggy-bank/Happiggy-bank/Assets.xcassets/button-icon-images/tabBarSettingsSelected.imageset/btn_home_sel.svg
  Happiggy-bank/Happiggy-bank/Assets.xcassets/customLightGray.colorset/Contents.json
  Happiggy-bank/Happiggy-bank/Extensions/UIColor+AssetColors.swift
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Storyboard/SettingsLabelButtonCell.xib
  Happiggy-bank/Happiggy-bank/Storyboard/SettingsToggleButtonCell.xib
  Happiggy-bank/Happiggy-bank/Subview/SettingsLabelButtonCell.swift
  Happiggy-bank/Happiggy-bank/Subview/SettingsToggleButtonCell.swift
  Happiggy-bank/Happiggy-bank/Subview/SettingsViewCell.swift
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/ViewController/SettingsViewController.swift
Labels: enhancement

#83 [feat] 저금통 뷰 영역, 중력 범위, 쪽지 뷰 충돌 범위 재설정
  Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift
  Happiggy-bank/Happiggy-bank/Storyboard/Base.lproj/Main.storyboard
  Happiggy-bank/Happiggy-bank/Subview/NoteView.swift
  Happiggy-bank/Happiggy-bank/Utils/Constants.swift
  Happiggy-bank/Happiggy-bank/Utils/Gravity.swift
  Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift
  Happiggy-bank/Happiggy-bank/ViewModel/HomeViewModel.swift
Labels: enhancement

#89 [feat] 데이터 모델 수정 #87
  Happiggy-bank/Happiggy-bank/CoreData/Bottle+CoreDataClass.swift
  Happiggy-bank/Happiggy-bank/Happiggy-bank.xcdatamodeld/Happigy-bank.xcdatamodel/contents
  Happiggy-bank/Happiggy-bank/ViewController/BottleViewController.swift
  Happiggy-bank/Happiggy-bank/ViewController/NewBottleDatePickerViewController.swift
Labels: enhancement
