Repository Happynyamy/Happiggy-bank-iOS, pull requests merged in 2022-12, with the labels that each got.

#246 [feat] note cell에 새로운 색상 반영
  Happiggy-bank/Happiggy-bank/Subview/NoteCell.swift
  Happiggy-bank/Happiggy-bank/Subview/PhotoNoteCell.swift
  Happiggy-bank/Happiggy-bank/ViewModel/PhotoNoteCellViewModel.swift
Labels: enhancement

#252 [chore] SnapKit SPM 설치 #250
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: chore

#264 [refactor] 커스텀 폰트 적용을 위한 베이스 클래스 생성 #263
  Happiggy-bank/Happiggy-bank.xcodeproj/project.pbxproj
  Happiggy-bank/Happiggy-bank/Subview/BaseButton.swift
  Happiggy-bank/Happiggy-bank/Subview/BaseLabel.swift
  Happiggy-bank/Happiggy-bank/Subview/BaseTextField.swift
  Happiggy-bank/Happiggy-bank/Subview/BaseTextView.swift
Labels: refactor
